import Categories from '@/components/categories/categories'
import Head from 'next/head'
import Image from 'next/image'
import { useDispatch } from 'react-redux';
import { getAllProducts } from '../../app/reducers/productsReducer';
import { useEffect } from 'react';
import { getAllCategories } from '../../app/reducers/categoriesReducer';


export default function Home() {
//  console.log(process.env);
 const dispatch = useDispatch();
  useEffect(() => {
    dispatch(getAllProducts());
    dispatch(getAllCategories());
  },[dispatch]);

  return (
    <>
      <Head>
        <title>Akhaneisob.com</title>
        <meta name="description" content="Generated by Akhaneisob.com" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='relative bg-green-950 min-h-screen'>
       <section className='w-[80%] mx-auto pt-10'>
       <Categories />
       </section>
      </main>
    </>
  )
}