"use client";
import Categories from "@/components/categories/categories";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Akhaneisob.com</title>
        <meta name="description" content="Generated by Akhaneisob.com" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative bg-green-950 ">
        <section className="w-[80%] mx-auto pt-10">
          <Categories />
        </section>
      </main>
    </>
  );
}
